### SELECT TODOS USUARIOS 
GET https://mossos.gencat.cat/web/.content/home/01_els_mossos_desquadra/indicadors_i_qualitat/Dades_obertes/fitxers/json/Fets_2020.json HTTP/1.1

### SELECT USUARIO POR DNI
GET http://localhost:9000/usuarios/48222011G HTTP/1.1

### POST USUARIO
POST http://localhost:9000/usuarios HTTP/1.1
Content-Type: application/json

{
    "DNI": "45222011S",
    "NOMBRE": "RAUL",
    "APELLIDOS": "FERNANDEZ",
    "CORREO": "RAUL.FERNANDEZ@GMAIL.COM",
    "POBLACION": "MONTGAT",
    "BARRIO": "MALLORQUINES",
    "CONTRASENYA": "67890"
}   

### DELETE USUARIO POR DNI
DELETE  http://localhost:9000/usuarios/482211G HTTP/1.1

### UPDATE USUARIO POR DNI
PUT http://localhost:9000/usuarios/48222011G HTTP/1.1
Content-Type: application/json
{
    "DNI": "48222011G",
    "NOMBRE": "CARLOS",
    "APELLIDOS": "ERENCIA",
    "CORREO": "CARLOS.ERENCIA2001@GMAIL.COM",
    "POBLACION": "MONTGAT",
    "BARRIO": "RESIDENCIAL CAMI ALELLA",
    "CONTRASENYA": "123456"
}

------------------------------------------------------------

### SELECT TODAS PREGUNTAS-Q1 
GET http://localhost:9000/preguntasq1 HTTP/1.1

### SELECT POR ID_PREGUNTA
GET http://localhost:9000/preguntasq1 HTTP/1.1

### POST PREGUNTA
POST http://localhost:9000/preguntasq1 HTTP/1.1
Content-Type: application/json

{
    "ENUNCIADO": "A ser víctima (o algú proper a mi) d'un tracte degradant que menyscabi la meva identitat moral.",
}

### DELETE PREGUNTA POR ID_PREGUNTA
DELETE  http://localhost:9000/preguntasq1/2 HTTP/1.1

### UPDATE PREGUNTA POR ID_PREGUNTA
PUT http://localhost:9000/preguntasq1/3 HTTP/1.1
Content-Type: application/json
{
    "ENUNCIADO": "A l'alteració, modificació o falsificació de certs elements essencials d'un document.",
}

